'use strict';

module.exports = {
  //login actions (unprotected)
  LOGIN_USER_REQUEST:   'LOGIN_USER_REQUEST',
  LOGIN_USER_FAILTURE:  'LOGIN_USER_FAILTURE',
  LOGIN_USER_SUCCESS:   'LOGIN_USER_SUCCESS',

  //user logout (protected - option only visible for authenticated users)
  LOGOUT_USER:          'LOGOUT_USER',

  //public pools getter (unprotected)
  POOLS_DATA_REQUEST:   'POOLS_DATA_REQUEST',
  POOLS_DATA_SUCCESS:   'POOLS_DATA_SUCCESS',
  POOLS_DATA_FAILTURE:  'POOLS_DATA_FAILTURE',

  //authenticated user owned pools (protected)
  USER_POOLS_DATA_REQUEST:  'USER_POOLS_DATA_REQUEST',
  USER_POOLS_DATA_SUCCESS:  'USER_POOLS_DATA_SUCCESS',
  USER_POOLS_DATA_FAILTURE: 'USER_POOLS_DATA_FAILTURE',

  //update user owned pools i.e. adding options removing etc. (protected)
  USER_POOL_UPDATE_REQUEST:   'USER_POOL_UPDATE_REQUEST',
  USER_POOL_UPDATE_SUCCESS:   'USER_POOL_UPDATE_SUCCESS',
  USER_POOL_UPDATE_FAILTURE:  'USER_POOL_UPDATE_FAILTURE',

//TODO: create actions for create and delete

  USER_POOL_CREATE_REQUEST:   'USER_POOL_CREATE_REQUEST',
  USER_POOL_CREATE_SUCCESS:   'USER_POOL_CREATE_SUCCESS',
  USER_POOL_CREATE_FAILTURE:  'USER_POOL_CREATE_FAILTURE',

  USER_POOL_DELETE_REQUEST:   'USER_POOL_DELETE_REQUEST',
  USER_POOL_DELETE_SUCCESS:   'USER_POOL_DELETE_SUCCESS',
  USER_POOL_DELETE_FAILTURE:  'USER_POOL_DELETE_FAILTURE',

  //voting (unprotected)
  VOTE_REQUEST:   'VOTE_REQUEST',
  VOTE_SUCCESS:   'VOTE_SUCCESS',
  VOTE_FAILTURE:  'VOTE_FAILTURE'
};

//export default actionTypes;
